CREATE TABLE client (
    client_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    last_name varchar(30),
    first_name varchar(30),
    middle_name varchar(30),
    birth_date date,
    email varchar,
    gender varchar,
    marital_status varchar,
    dependent_amount int,
    passport jsonb,
    employment jsonb,
    account varchar
);