CREATE TABLE credit (
    credit_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    amount decimal,
    term int,
    monthly_payment decimal,
    rate decimal,
    psk decimal,
    payment_schedule jsonb,
    insurance_enable boolean,
    salary_client boolean,
    credit_status varchar
);