CREATE TABLE application (
    application_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    client_id bigint REFERENCES client(client_id),
    credit_id bigint REFERENCES credit(credit_id),
    status varchar,
    creation_date timestamp,
    applied_offer jsonb,
    sign_date timestamp,
    ses_code varchar,
    status_history jsonb
);